export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESST';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';
export const DECODE_TOKEN_SUCCESS = 'DECODE_TOKEN_SUCCESS';
export const DECODE_TOKEN_FAILURE = 'DECODE_TOKEN_FAILURE';